version: '3.4'

services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
      target: golang
    volumes:
      - ./generated:/app/generated
    extra_hosts:
      - "dockerhost:$DOCKERHOST"  
    command: top

  webserver:
    build:
      context: .
      dockerfile: Dockerfile
      target: webserver
    env_file: 
      - .env
    volumes:
      - ./:/var/www
    ports:
      - "9090:9001"
    extra_hosts:
      - "dockerhost:$DOCKERHOST"
